[package]
name = "hello-world-wasm-sort"
version = "0.1.0"
authors = ["Bharat Patel <bharatpatelio200@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
